const LOGIN         = "USER_LOGING";
const LOGOUT        = "USER_LOGOUT";
const SIGN          = "USER_SIGN";
const LOGINGOOGLE   = "USER_LOGINGOOGLE";
const UPDATE        = "USER_UPDATE";
const LOADIMAGE     = "USER_LOADIMAGE";
const UPDATEADDRESS = "USER_UPDATEADDRESS";
const ADDNOTIFICATION = "USER_ADDNOTIFICATION";

const SETNAME       = "USER_SETNAME";
const SETEMAIL      = "USER_SETEMAIL";
const SETPHONE      = "USER_SETPHONE";
const SETLOGGED     = "USER_SETLOGGED";
const SETSIGNOUT    = "USER_SETSIGNOUT";
const SETUPDATE     = "USER_SETUPDATE";
const SETIMAGE      = "USER_SETIMAGE";

export {LOGIN, LOGOUT, SIGN, SETNAME, SETEMAIL, SETPHONE, SETLOGGED, LOGINGOOGLE, SETSIGNOUT, UPDATE, SETUPDATE, SETIMAGE, ADDNOTIFICATION, LOADIMAGE, UPDATEADDRESS};